# Generated by Django 4.1.7 on 2023-04-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='Email',
            field=models.EmailField(default='naveen99@gmail.com', max_length=254),
        ),
    ]
