# Generated by Django 4.1.7 on 2023-04-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_webpage_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Date',
            field=models.DateField(default='2023-04-08'),
        ),
    ]
